### PR TITLE
refactor: improve the display of groups in account view

### PR DESCRIPTION
**Pull request by raastinn**
Screenshot from 2024-01-31 12-06-57
Screenshot from 2024-01-31 12-07-17

### CODE REVIEW

**Comment by raastinn** [comment]
Screenshot from 2024-01-31 12-16-52
Also did this as an alternative I could submit the PR for

**Review by igboyes — CHANGES_REQUESTED** [review]
Sorry for late review.

Can you please make the groups box take up the full width like the other ones?

Also, I think they should be reordered by importance.

1. Password
2. Email
3. Groups

**Comment by raastinn** [comment]
Screenshot from 2024-03-27 16-53-01

**Pull request merged**
