### PR TITLE
chore: upgrade react-dropzone

### PR DESCRIPTION
**Pull request by raastinn**

### CODE REVIEW

**Review by ReeceHoffmann — COMMENTED** [review]
Latest is version 14, https://www.npmjs.com/package/react-dropzone. NPM will only update to latest version that is not a major version by default

**Comment by ReeceHoffmann** [comment]
Did you verify that everything works as expected post update?

**Comment by raastinn** [comment]
> Did you verify that everything works as expected post update?

Yeah the file uploads seem to be working as expected with drag and drop.

**Review by ReeceHoffmann — APPROVED** [review]

**Pull request merged**
