### PR TITLE
refactor: Replace `react-tippy`, `react-popper` and `popperjs` with Radix alternative

### PR DESCRIPTION
**Pull request by raastinn**
Screenshot from 2024-03-21 10-56-21
Screenshot from 2024-03-21 11-12-33

### CODE REVIEW

**Review by ReeceHoffmann — COMMENTED** [review]
Code looks good. Visually the tooltip is great as well. The positioning of the popover seems really strange to me. Not clearly centered under the box or the icon.

**Comment by raastinn** [comment]
Screenshot from 2024-03-25 08-46-40
My window was smaller thats why it showed it in a strange position. This is how it shows on a big window

**Comment by ReeceHoffmann** [comment]
Center under the box. Icon could theoretically work, but I think that redesign is a problem for another time

**Comment by raastinn** [comment]
Screenshot from 2024-03-25 10-56-11

**Review by ReeceHoffmann — APPROVED** [review]

**Pull request merged**
