### PR TITLE
refactor: condense analysis item

### PR DESCRIPTION
**Pull request by raastinn**
Screenshot from 2024-02-19 13-30-46

### CODE REVIEW

**Review by ReeceHoffmann — COMMENTED** [review]
Code change look good, but there is an alignment problem between samples that are complete and those with running jobs. I doubt the problem is new, but this just makes it a bit more obvious. Resolve then this is good to go.

**Comment by raastinn** [comment]
Screenshot from 2024-02-21 14-43-24

**Comment by ReeceHoffmann** [comment]
Better for sure, progress circle still looks offset vs icons though

**Comment by raastinn** [comment]
Screenshot from 2024-03-05 11-50-20

**Review by ReeceHoffmann — APPROVED** [review]

**Pull request merged**
