### PR TITLE
refactor: restyle job items

### PR DESCRIPTION
**Pull request by raastinn**
Screenshot from 2024-01-29 09-42-02

### CODE REVIEW

**Review by igboyes — CHANGES_REQUESTED** [review]
* Unbold the user and time.
* Show green checkmark instead of green circle.
* It looks like there might be excessive padding compared to other similar elements. See labels list.

**Comment by raastinn** [comment]
Screenshot from 2024-01-29 13-53-38

**Review by igboyes — COMMENTED** [review]
Looks good. Resolves conflicts and I'll merge.

**Pull request merged**
