### PR TITLE
refactor: render pathoscope graph labels in HTML

### PR DESCRIPTION
**Pull request by raastinn**
## Changes
- Rendered the graph label in `<p>`

## Pre-Review Checklist
* [x] I have considered backwards and forwards compatibility.
* [x] All changes are tested.
* [x] All touched code documentation is updated.
* [x] All tests pass in my local environment
* [x] Deepsource issues have been reviewed and addressed.
* [x] Commented code and `console` usages have been removed.
 
## Screenshots
_Only required for visual changes_
Screenshot from 2024-08-07 12-07-10

### CODE REVIEW

**Comment by ReeceHoffmann** [comment]
Did you try lifting the graph title out of the graph? Something like: 
image

May or may not end up taking to much space/looking bad. As long as it looks okay it would be nice to avoid the name and data overlapping as that is pretty hard to read

**Comment by raastinn** [comment]
Screenshot from 2024-08-14 14-40-37
Moved the graph label above the graph which currently looks like this. Let me know if it looks good or if needs any tweaking (padding between the isolate label for example)

**Comment by ReeceHoffmann** [comment]
You could definitely play with more padding. It does seem a bit small but not stuck on that. I am okay with this form. that said did you experiment with emphasizing the graph label? Right now it feels like it is on equal footing with the `isolate` label. Not the end of the world but would be nice to visuals emphasis the hierarchy.

Couple of common techniques:
  - Decrease the text size (might end up too small)
  - Lighten the text color (Not too much though, we use lighter colors in some parts of the UI to express missing values)

Also fine with it as is, just some ideas

**Comment by raastinn** [comment]
Screenshot from 2024-08-19 13-37-18

**Review by ReeceHoffmann — APPROVED** [review]

**Pull request merged**
