### PR TITLE
refactor: use the admin API for user views, cleanup redux & files

### PR DESCRIPTION
**Pull request by raastinn**

### CODE REVIEW

**Comment by raastinn** [comment]
**_Note:_** gonna leave this as draft until the admins create API gets merged

**Comment by ReeceHoffmann** [comment]
DeepSource has a couple complaints worth handling, otherwise happy to merge. (You can ignore the `.bind()` issue)

**Comment by ReeceHoffmann** [comment]
I am happy with this, but can't merge till a backend issue is resolved. Will merge once the backend fully supports this PR

**Review by ReeceHoffmann — APPROVED** [review]

**Pull request merged**
