### PR TITLE
refactor: reimplement Table component in tailwind

### PR DESCRIPTION
**Pull request by jasont7**
## Pre-Review Checklist
* [x] I have considered backwards and forwards compatibility.
* [x] All changes are tested.
* [x] All touched code documentation is updated.
* [x] All tests pass in my local environment
* [x] Deepsource issues have been reviewed and addressed.
* [x] Commented code and `console` usages have been removed.
 
## Screenshots
Screenshot from 2024-07-30 23-03-34

### CODE REVIEW

**Comment by jasont7** [comment]
@igboyes @raastinn the tsc failure is due to the `BoxGroup` styled component attempting to use the new tailwind-based `Table` component. Should I also migrate the `Box` base components to tailwind in this PR?

**Comment by raastinn** [comment]
> @igboyes @raastinn the tsc failure is due to the `BoxGroup` styled component attempting to use the new tailwind-based `Table` component. Should I also migrate the `Box` base components to tailwind in this PR?

I would make a component called `BoxGroupTable` with updated styling and remove the styling in `BoxGroup`. Then replace all the `Tables` that are used inside of a `BoxGroup`.

**Comment by jasont7** [comment]
Blocked: test is currently failing due to `SampleDetailGeneral` component not containing element with the text: `/timeout/i`, but I'm unable to create a sample in the UI (400 backend error) so I can't reproduce this issue

**Comment by ReeceHoffmann** [comment]
> Blocked: test is currently failing due to `SampleDetailGeneral` component not containing element with the text: `/timeout/i`, but I'm unable to create a sample in the UI (400 backend error) so I can't reproduce this issue

That's a bit disconcerting. Sample creation works perfectly for me on latest. You running an old version?

Which test is giving you problems? Looks like things passed here. Could be flake

**Comment by jasont7** [comment]
> > Blocked: test is currently failing due to `SampleDetailGeneral` component not containing element with the text: `/timeout/i`, but I'm unable to create a sample in the UI (400 backend error) so I can't reproduce this issue
> 
> That's a bit disconcerting. Sample creation works perfectly for me on latest. You running an old version?
> 
> Which test is giving you problems? Looks like things passed here. Could be flake

Yes, I think it was a flake. I am running the latest version but sample creation still doesn't work for me locally - @raastinn was having the same issue

**Review by ReeceHoffmann — APPROVED** [review]

**Pull request merged**
